### PR TITLE
Refactored init code to handle all types

### LINKED ISSUE #92: Fatal error: Uncaught Error: Class 'string' not found in vendor/paypal/sdk-core-php/lib/PayPal/Core/PPMessage.php:104
i know those exist:
https://github.com/paypal/sdk-core-php/issues/34
https://github.com/paypal/sdk-core-php/issues/7
https://github.com/paypal/sdk-core-php/pull/32

but I still have the issue even with the following versions:

> paypal/adaptivepayments-sdk-php     v3.9.2 PayPal adaptivepayments SDK for PHP
> paypal/sdk-core-php                 3.3.0  PayPal Core SDK for PHP
> PHP Version 7.0.12-1+deb.sury.org~xenial+1

Note: I did not! have this issue on my local dev machine and on two servers of digital ocean. So this worked fine on 3 servers. It does not work though, on the new host we are moving to. So i guess it must be some php.ini or environment problem.

the code causing the problem

```

            } else { // one object
                $this->{$property} = new $type();
```

full stack trace i receive:

`Fatal error: Uncaught Error: Class 'string' not found in /www/MyApp_411/public/japi_lib/vendor/paypal/sdk-core-php/lib/PayPal/Core/PPMessage.php:104 Stack trace: #0 /www/MyApp_411/public/japi_lib/vendor/paypal/adaptivepayments-sdk-php/lib/PayPal/Service/AdaptivePaymentsService.php(215): PayPal\Core\PPMessage->init(Array) #1 /www/MyApp_411/public/japi_lib/src/MyApp/Service/JcrPayPalService.php(119): PayPal\Service\AdaptivePaymentsService->Pay(Object(PayPal\Types\AP\PayRequest)) #2 /www/MyApp_411/public/japi_lib/src/MyApp/Service/JcrPayPalService.php(78): MyApp\Service\JcrPayPalService::doPreparePayment(0.05, 1, 'https://MyApp....', 'https://MyApp....', Object(MyAppProject)) #3 /www/MyApp_411/public/japi_lib/src/MyApp/Service/JcrPayPalService.php(27): MyApp\Service\JcrPayPalService::preparePayment(1, false, 5, 'https://MyApp....', 'https://MyApp....', Object(MyAppProject)) #4 /www/MyApp_411/public/japi_lib/src/routes/routes_funding.php(83): MyApp\Service\JcrPayPalService::initPaypalProcess('335495', 'jcr_5 in /www/MyApp_411/public/japi_lib/vendor/paypal/sdk-core-php/lib/PayPal/Core/PPMessage.php on line 104`

### PR DESCRIPTION
**Pull request by jaypatel512**
- Removed in-line assignments and expressions.
- Fixes #92.

### CODE REVIEW

**Comment by jaypatel512** [comment]
Hey  @Jossnaz !

Would you mind giving this a go pretty quick for your case.

**Comment by Jossnaz** [comment]
@jaypatel512 it gives: `Uncaught Error: Class 'string' not found in /www/jewcer_411/public/japi_lib/vendor/paypal/sdk-core-php/lib/PayPal/Core/PPMessage.php:97`

another reason not to use variable definition in expressions is this:
```

<?php

if(false && $x = 'bippo'){
	
}

echo $x; //NOTICE Undefined variable: x
```

**Comment by jaypatel512** [comment]
Can you pass in the input data if possible. I want to reproduce this issue if possible in my local.

**Comment by Jossnaz** [comment]
@jaypatel512 and the reason I used 2 ifs in the example i gave you was because after the first if you assign a variable `$type`. If you do not use an assign, e.g. if there is no reason to use two ifs, don't use two ifs.
i used var_export(..., true); on:

`get_object_vars($this)`:
array (
 ```
 'responseEnvelope' => NULL,
  'payKey' => NULL,
  'paymentExecStatus' => NULL,
  'payErrorList' => NULL,
  'paymentInfoList' => NULL,
  'sender' => NULL,
  'defaultFundingPlan' => NULL,
  'warningDataList' => NULL,
  'error' => NULL,
)
```

on `$map`:
```

array (
  'responseenvelope.timestamp' => '2016-10-25T11:40:07.628-07:00',
  'responseenvelope.ack' => 'Success',
  'responseenvelope.correlationid' => '52d08445d77b2',
  'responseenvelope.build' => '26220497',
  'paykey' => 'AP-4YG78981D8139310P',
  'paymentexecstatus' => 'CREATED',
)
```

and

`$prefix`

`''`

the thing is: reproducing the problem won't be so easy because I didn't run into this problem on different servers... so you would probably need the same environment setup that causes it.

i created a codepen with the phpinfo() of the server for you:

http://codepen.io/anon/pen/XjGogP

**Comment by Jossnaz** [comment]
@jaypatel512  having said that, i would probably just push the hotfix of the change, and then do a deep refactor of the code in peace another day with a lot of testing etc. because code like this is not really nice to test.

**Comment by jaypatel512** [comment]
Closing this issue based on inactivity. Please re-open if you are still facing this issue.

**Pull request closed without merging**
